const TICK_SQUARE = 'TICK_SQUARE';
const RESET = 'RESET';
const END_GAME = 'END_GAME';
const SET_PLAYERS = 'SET_PLAYERS';
const RESET_PLAYERS = 'RESET_PLAYERS';
const ADD_TO_LEADERBOARD = 'ADD_TO_LEADERBOARD';

export default { TICK_SQUARE, RESET, END_GAME, SET_PLAYERS, RESET_PLAYERS, ADD_TO_LEADERBOARD };
